version: "3.8"

services:
  # 1. The Payment Gateway API
  api:
    build: .
    ports:
      - "8090:8090"
    environment:
      # Injecting the Docker network URLs
      - SERVER_PORT=8090
      - BANK_SIMULATOR_URL=http://bank_simulator:8080
    depends_on:
      - bank_simulator

  # 2. The Provided Bank Simulator
  bank_simulator:
    container_name: bank_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2525:2525"
      - "8080:8080"
    command: --configfile /imposters/bank_simulator.ejs --allowInjection
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters