// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"PaymentGateway/internal/application/usecase"
	"PaymentGateway/internal/infrastructure/acquiring_bank"
	"PaymentGateway/internal/infrastructure/inmemory"
	"PaymentGateway/internal/infrastructure/uuid"
	"PaymentGateway/internal/presentation/rest"
	"PaymentGateway/internal/presentation/rest/handler"
	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	"log/slog"
	"net/http"
)

// Injectors from wire.go:

// InitializeAPI sets up the entire application dependency graph (Composition Root).
// It takes the fundamental external dependencies and returns a fully wired *gin.Engine ready to run.
func InitializeAPI(logger *slog.Logger, redisClient *redis.Client, httpClient *http.Client, bankSimulatorURL string) (*gin.Engine, error) {
	inMemoryPaymentRepository := inmemory.NewInMemoryPaymentRepository()
	redisIdempotencyStore := inmemory.NewRedisIdempotencyStore(redisClient)
	uuidGenerator := uuid.NewUUIDGenerator()
	simulatorClient := acquiring_bank.NewSimulatorClient(bankSimulatorURL, httpClient)
	processPaymentUseCase := usecase.NewProcessPaymentUseCase(inMemoryPaymentRepository, redisIdempotencyStore, uuidGenerator, simulatorClient)
	paymentHandler := handler.NewPaymentHandler(processPaymentUseCase)
	retrievePaymentUseCase := usecase.NewRetrievePaymentUseCase(inMemoryPaymentRepository)
	retrievePaymentHandler := handler.NewRetrievePaymentHandler(retrievePaymentUseCase)
	engine := rest.NewRouter(logger, paymentHandler, retrievePaymentHandler)
	return engine, nil
}
