name: Unit Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main # We ignore main here because the CI/CD pipeline handles it
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0' # Matches your go.mod
          cache: true          # Speeds up subsequent runs by caching dependencies

      - name: Install Dependencies
        run: go mod download

      - name: Run Unit Tests
        # -v gives verbose output, -race detects race conditions in your goroutines
        run: go test -v -race ./...